
version: '3.1'

services:

  db:
    image: mysql
    container_name: crypto_data
    restart: always
    ports:
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=rootpass
       - MYSQL_USER=crypto
       - MYSQL_DATABASE=marketdata
       - MYSQL_PASSWORD=mypass
    volumes:
      - ./market-data:/var/lib/mysql